{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from clusterlogs import pipeline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.set_option('display.max_colwidth', -1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('patterns.txt', header=0, names=['error_message'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>error_message</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>: the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                                                                                           error_message\n",
       "0  : the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.\n",
       "1  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                         \n",
       "2  err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:                                        \n",
       "3  Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///                                             \n",
       "4  SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.                                                "
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(394, 1)"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "cluster = pipeline.Chain(df, target='error_message', mode='create')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tokenization finished\n",
      "Found 392 equal groups\n",
      "Matching Clusterization!\n",
      "Postprocessed with 358 clusters\n"
     ]
    }
   ],
   "source": [
    "cluster.process()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pattern</th>\n",
       "      <th>indices</th>\n",
       "      <th>cluster_size</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>238</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 451 General problem:</td>\n",
       "      <td>[262, 110, 112, 258, 134, 98]</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>255</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error｟*｠</td>\n",
       "      <td>[67, 240, 179]</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>261</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : error in: system call failed: 500 End.</td>\n",
       "      <td>[205, 175, 121]</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>(Neon): SSL handshake failed: Connection timed out during SSL handshake</td>\n",
       "      <td>[300, 220]</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>36</td>\n",
       "      <td>: the server responded with an error 500｟*｠ server error</td>\n",
       "      <td>[213, 267]</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>124</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to /dpm/home/atlas/atlasscratchdisk/rucio/tests/;</td>\n",
       "      <td>[12]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>123</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to //; permission denied</td>\n",
       "      <td>[7]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>122</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests/</td>\n",
       "      <td>[20]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>121</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3003] Output file /dteam:test1/domatest/ is already opened by 1 writer; open denied.</td>\n",
       "      <td>[44]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>357</td>\n",
       "      <td>｟*｠ timed out</td>\n",
       "      <td>[28]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>358 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                                                                                                                             pattern  \\\n",
       "238  TRANSFER globus_ftp_client: the server responded with an error 451 General problem:                                                                               \n",
       "255  TRANSFER globus_ftp_client: the server responded with an error｟*｠                                                                                                 \n",
       "261  TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : error in: system call failed: 500 End.                                   \n",
       "0    (Neon): SSL handshake failed: Connection timed out during SSL handshake                                                                                           \n",
       "36   : the server responded with an error 500｟*｠ server error                                                                                                          \n",
       "..                                                        ...                                                                                                          \n",
       "124  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to /dpm/home/atlas/atlasscratchdisk/rucio/tests/;                         \n",
       "123  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to //; permission denied                                                  \n",
       "122  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests/          \n",
       "121  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3003] Output file /dteam:test1/domatest/ is already opened by 1 writer; open denied.   \n",
       "357  ｟*｠ timed out                                                                                                                                                     \n",
       "\n",
       "                           indices  cluster_size  \n",
       "238  [262, 110, 112, 258, 134, 98]  6             \n",
       "255  [67, 240, 179]                 3             \n",
       "261  [205, 175, 121]                3             \n",
       "0    [300, 220]                     2             \n",
       "36   [213, 267]                     2             \n",
       "..          ...                    ..             \n",
       "124  [12]                           1             \n",
       "123  [7]                            1             \n",
       "122  [20]                           1             \n",
       "121  [44]                           1             \n",
       "357  [28]                           1             \n",
       "\n",
       "[358 rows x 3 columns]"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster.result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[': System error in send:｟*｠ globus_xio: A system call failed:｟*｠'] \n",
      "\n",
      "['CHECKSUM timeout of｟*｠']\n"
     ]
    }
   ],
   "source": [
    "print(cluster.in_cluster(cluster.result, 2),\"\\n\") #some messages from the cluster 2\n",
    "print(cluster.in_cluster(cluster.result, 38)) #messages from the cluster without a clear pattern"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['TRANSFER globus_ftp_client: the server responded with an error 451 General problem:',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : error in: system call failed: 500 End.',\n",
       "       '(Neon): SSL handshake failed: Connection timed out during SSL handshake',\n",
       "       ': the server responded with an error 500｟*｠ server error',\n",
       "       'DESTINATION CHECKSUM checksum calculation for ADLER32 not supported for davs:/:/atlasscratchdisk/rucio/tests/',\n",
       "       '[gfalt_copy_file][perform_copy] TRANSFER [gfal_http_copy] ERROR: Copy failed with mode 3rd push, with error: [davix2gliberr]',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. :',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/dpm/home/ while putdone : [SE][PutDone][]',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : Error｟*｠',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][] error accessing:/:',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY] The surl srm:/ is currently busy (ongoing put',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : 500-globus_xio: System error in: 500-globus_xio: A system call failed: 500 End.',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][][]',\n",
       "       ': Copy failed with mode 3rd push, with error: Transfer failed: failure: sending data',\n",
       "       'error, reached maximum number of attempts after 1 attempts',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Failed to connect [:]: Connection',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []',\n",
       "       'TRANSFER ERROR: Copy failed with mode｟*｠, with error:',\n",
       "       'from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy',\n",
       "       'ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure:｟*｠: timed out while waiting for mover｟*｠',\n",
       "       'ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: verification failed: failed to connect to server: java.net.SocketTimeoutException: Read timed out',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: problem sending data:｟*｠ failed',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to select｟*｠:｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure:',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: Remote copy failed with status code 0:',\n",
       "       '｟*｠] operation canceled by user',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :｟*｠ 500 End.',\n",
       "       ': the server responded with an error 500: v=1 c= 500-GridFTP-Errno: 500-GridFTP-Reason: System error in name 500-GridFTP-Error-String: 500- 500 End.',\n",
       "       'err: Input/output error, err: [SE][][SRM_FAILURE] httpg:/se03.esc.qmul.ac.uk:8444/srm/managerv2: Failed to authorize XACML request: Timeout was reached.',\n",
       "       'TRANSFER ERROR: Copy failed with mode｟*｠, with error: TRANSFER STREAMED DISABLED Trying to fallback to a｟*｠ copy, but they are disabled',\n",
       "       'globus_xio: Unable to connect to:2811 globus_xio: System error in connect: No route to host globus_xio: A system call failed: No route to host',\n",
       "       'reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] SURL is not local: srm:/lcg-se1.sfu.computecanada.ca/atlas/rucio/.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 FTP proxy did not shut down',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 451-GlobusError: v=1 c=INTERNAL_ERROR 451-GridFTP-Errno: 255 451-GridFTP-Reason: System error in HDFS (host=, user=, path=/store/) 451-GridFTP-Error-String: Unknown',\n",
       "       'TRANSFER globus_ftp_client: the operation was aborted',\n",
       "       'TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred',\n",
       "       'TRANSFER ERROR: Copy failed with mode｟*｠, with error: HTTP 500 :｟*｠ server error: 500 after 1 attempts',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Problem while connected to [2001:4ca0:0:201:a:0:2:]: Network is unreachable',\n",
       "       'reported from srm_ifce : 70 [SE][Ls][SRM_INTERNAL_ERROR] Failed to｟*｠ transfers',\n",
       "       'TRANSFER ERROR: Copy failed with mode, with error: HTTP｟*｠ : Server Error',\n",
       "       'TRANSFER ERROR: Copy failed with mode, with error: Authentication error, reached maximum number of attempts',\n",
       "       'TRANSFER ERROR: Copy failed with mode, with error: (Neon): SSL handshake failed: Connection timed out during SSL handshake',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd, with error: Request｟*｠ was requested.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Renewal failedSOAP 1.1 fault: SOAP-ENV:Server.generalException [no subcode] delegation for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management with id 1234 Detail: <ns1:DelegationException xmlns:ns1=http:/www.gridsite.org/namespaces/delegation-2><msg> for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management with id 1234</msg></ns1:DelegationException>',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy HTTP 500 :｟*｠ server error: 500',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Failed to connect [2406:f00:9:]:',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Problem while connected to [2001:6a8:3081:1201:1:]: Connection timed out',\n",
       "       'err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 Post-processing failed: File｟*｠ (expected=, actual=)',\n",
       "       'globus_ftp_client: the server responded with an error 530 Login incorrect. :｟*｠ user is invalid.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451｟*｠ failed: PreparedStatementCallback; SQL [SELECT f_create_inode(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; ERROR: insert or update on table t_dirs violates foreign key constraint t_dirs_iparent_fkey; Detail: Key (iparent)=() is not present in table t_inodes.; Where: SQL statement INSERT INTO t_dirs VALUES (parent, newid, name);PL/pgSQL function f_create_inode(bigint,character varying,character',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451｟*｠ failed: File｟*｠ not｟*｠',\n",
       "       'globus_ftp_client: the server responded with an error 550 No such file or directory',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 write [net=2001:1458:301:0:0:100:=GFtp/2,store=@=]',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 Unable to｟*｠ space: no｟*｠.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 Post-processing failed: No such file or directory:｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: to [2001:48a8:68f7:192:41:]:',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Problem while connected to [2001:]:',\n",
       "       'globus_ftp_control: gss_init_sec_context failed globus_gsi_gssapi: Error with gss credential｟*｠ globus_credential: Valid credentials could not be found in any of the possible locations specified by the credential search order. Valid credentials could not be found in any of the possible locations specified by the credential search order. Attempt 1 globus_credential: Error reading host credential globus_sysconfig: Error with certificate filename globus_sysconfig: Error with certificate filename globus_sy',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Stream was closed in the｟*｠ of a｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Stream ended before EOD',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Problem while connected to [:]: Input/output error',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Problem while connected to [:]: Connection reset by peer',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Problem while connected to [2a00:139c:5:215:0:41:7c:b2]: Input/output error',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Problem while connected to [2001:]: La m quina remota ha reiniciat la connexi',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Could not the proxy: SOAP 1.1 fault: SOAP-ENV:Client [no subcode] Error observed by underlying SSL/TLS BIO: Connection reset by peer Detail: SSL_connect error in tcp_connect()',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Could not get the delegation id: Could not get proxy request: fault: SOAP-ENV:Client [no subcode] End of file or no input:｟*｠ interrupted or timed out Detail: [no detail]',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Could not get the delegation id: Could not get proxy request: SOAP 1.1 fault: SOAP-ENV:Client [no subcode] Detail: connect failed in tcp_connect()',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to select｟*｠: No｟*｠ candidates available/｟*｠/left for stage',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Remote copy failed with status code 0: Failed to connect to 2001: port: Bad file descriptor',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Remote copy could not be｟*｠ (status:):',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: HTTP protocol failure: org.apache.http.client.ClientProtocolException; caused by: Cannot retry request with a non-repeatable request entity; caused by: java.nio.channels.ClosedChannelException',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed while waiting for mover to start: Failed to enqueue mover: CacheException(rc=27;msg=Could not create mover for RemoteHttpsDataTransfer-1.1:https:/:/rucio/)',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed while waiting for mover to start: Could not create mover for RemoteHttpsDataTransfer-1.1:https:/dynafed02.heprc.uvic.ca:8443/atlas/scratchdisk/rucio/mc16_13TeV/fe/21/AOD.11982116._000010.pool.root.1',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to｟*｠ file: No route to [>PnfsManager@local]',\n",
       "       'srm-ifce err:｟*｠ not supported, err: [SE][][SRM_NOT_SUPPORTED] httpg:/:8443/srm/managerv2: Protocol(s) not supported: [gsiftp]',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to open/read local data from file/｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Could not get the delegation id: Could not get proxy request: Error fault: SOAP-ENV:Server [no subcode] HTTP/1.1 Detail: <!DOCTYPE HTML PUBLIC -/IETF/DTD HTML 2.0/EN> <html><head> <title></title> </head><body> <h1></h1> <p> /gridsite-delegation on this server.</p> </body></html>',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Error pushing https:/dynafed-atlas.cern.ch:443/data/dteam/s3/domatest/: 404 Not Found',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Error pushing https:/dpmhead-rc.cern.ch:443/dpm/cern.ch/home/dteam/domatests/https/domatest/: 507 Insufficient Storage',\n",
       "       '｟*｠',\n",
       "       '｟*｠ (Neon): Server certificate verification failed: certificate issued for a different hostname after 1 attempts',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Error string contains not valid UTF-8 chars',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Connection｟*｠; Status of TPC request｟*｠',\n",
       "       'TRANSFER CHECKSUM MISMATCH and｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: The peers certificate with subjects DN CN=s3.cern.ch,OU=Unified Communications,OU=Issued through Organisation Europ enne pour la Recherche Nucl ai,O=Organisation Europ enne pour la Recherche Nucl aire (CERN),STREET=Route de Meyrin 385,L=Meyrin,ST=Geneva,2.5.4.17=#130431323137,C=CH was rejected. The peers certificate status is: FAILED The following validation errors',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Too many attempts to select｟*｠; last｟*｠@ failed with Could not create MoverProtocol mover for RemoteHttpsDataTransfer-1.1:https:/dynafed02.heprc.uvic.ca:8443/atlas/scratchdisk/rucio/mc16_13TeV/fe/21/AOD.11982116._000010.pool.root.1: directory not found: /etc/grid-security/certificates',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: connection failed for PUT: Connect to: [/2001:0:0:] failed: (Connection refused); redirections [:/:/?sfn=%2Fdpm%2Fhome%&token=',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: failed to send PUT request: Cannot retry request with a non-repeatable request entity; caused by: (Write failed); after sending B () (%)',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Could not connect to server',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy 0) Renewal failedSOAP 1.1 fault: SOAP-ENV:Server.generalException [no subcode] Unable to create delegated credential: Provided private key is not matching the certificate Detail: <ns1:DelegationException xmlns:ns1=http:/www.gridsite.org/namespaces/delegation-2><msg>Unable to create delegated credential: Provided private key is not matching the certificate</msg></ns1:DelegationException> .',\n",
       "       'reported from srm_ifce : 70 [SE][Ls][SRM_INTERNAL_ERROR] Request to [>PnfsManager@local] timed out.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy (Neon): Could not read status｟*｠:',\n",
       "       'srm-ifce err: Communication error on send, err: [SE][Ls][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports Could NOT load client credentials GSS Major Status: General failure GSS Minor Status Error Chain: globus_gsi_gssapi: Error with GSI credential globus_gsi_gssapi: Error with gss credential｟*｠ globus_credential: Valid credentials could not be found in any of the possible locations specified by the credential search order. Valid credentials could not be',\n",
       "       'srm-ifce err: Communication error on send, err: [SE][Ls][] httpg:/ingrid-se02.cism.ucl.ac.be:8444/srm/managerv2: HTTP/1.0 403 Forbidden',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure:; redirections [:/:/?sfn=%2Fdpm%2Fhome%&token=%3D%401]',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: while pushing https:/:/atlasscratchdisk/rucio/tests/:',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: verification failed: rejected｟*｠: 500 Server Error',\n",
       "       'srm-ifce err: Connection timed out, err: [SE][AbortRequest][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports Error reading token data header: Connection closed',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: problem sending data: Connect to｟*｠:443 [｟*｠/｟*｠,｟*｠/2001:718:401:6017:2:0:0:1000] failed: connect timed out',\n",
       "       'srm-ifce err: Permission denied, err: [SE][Ls][SRM_AUTHORIZATION_FAILURE] httpg:/:8443/srm/managerv2:',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: failed to send PUT request: Cannot retry request with a non-repeatable request entity; caused by:; after sending B () (%); redirections [:/:/?sfn=%2Fdpm%2Fhome%&token=',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: failed to send PUT request: Cannot retry request with a non-repeatable request entity; caused by: java.nio.channels.ClosedChannelException; after sending B ( MiB) (100%); redirections [http:/:/pnfs/?dcache-http-uuid=]',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: failed to send PUT request: Cannot retry request with a non-repeatable request entity; caused by: Connection timed out (Write failed); after sending B ( MiB) (%); redirections [http:/145.100.33.46:/groups/dteam/DOMA-TPC/domatest/file14_59b77257-48eb-41f9-9e4f-6219f7001050?dcache-http-uuid=]',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. 500- : globus_ftp_control_local_pasv failed. 500-globus_xio: globus_l_xio_tcp_bind failed. 500-globus_xio: System error in bind: Address already in use 500-globus_xio: A system call failed: Address already in use 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. 500- : globus_xio_gsi: gss_init_sec_context failed.｟*｠: Unable to verify remote sides credentials｟*｠: SSL handshake problems: Couldnt do ssl handshake 500-OpenSSL Error: s3_pkt.c:1493: in library: SSL routines, function ssl3_read_bytes: sslv3 alert certificate expired SSL alert number 45 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : I/O operation was cancelled 500-globus_xio:｟*｠ was canceled 500 End.',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_http_copy] DESTINATION CHECKSUM MISMATCH Source and destination ADLER32 do not match (｟*｠ !=｟*｠)',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to ftp1.ndgf.org:1094 failed; all protocols have been tried.',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/ftp1.ndgf.org:1094/atlas/disk/atlasscratchdisk/rucio/tests/?fst.readahead=true',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] Failed to open file (｟*｠ [｟*｠])',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to /atlas/atlasscratchdisk/rucio/tests/;',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_http_copy] DESTINATION OVERWRITE [gfal_http_copy_overwrite][davix2gliberr]｟*｠:｟*｠ HTTP 403 : Permission refused',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_http_copy] DESTINATION OVERWRITE [gfal_http_copy_overwrite] [gfal_http_exists][gfal_http_access][davix2gliberr] Result Authentication error, reached maximum number of attempts after 1 attempts',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_http_copy] DESTINATION OVERWRITE [gfal_http_copy_overwrite] [gfal_http_exists][gfal_http_access][davix2gliberr] HTTP 403 : Permission refused',\n",
       "       'error on the turl request : [SE][][SRM_REQUEST_QUEUED] Failed to process any of the｟*｠',\n",
       "       'TRANSFER globus_xio: Unable to connect to:2811 globus_xio: System error in connect: Network is unreachable globus_xio: A system call failed: Network is unreachable',\n",
       "       '[gfalt_copy_file][perform_copy] DESTINATION CHECKSUM [gfal_http_copy][｟*｠][davix2gliberr] HTTP 500 :｟*｠ server error: 500',\n",
       "       '[gfal2_stat][gfal_plugin_statG][｟*｠][｟*｠] globus_ftp_client: the server responded with an error 530 Login incorrect. : Server over the global connection limit of 250 (user has 0 transfers) (host=, user=cms, path=(null)',\n",
       "       '[gfal2_stat][gfal_plugin_statG][｟*｠] Failed to stat file (Permission denied)',\n",
       "       '[gfal2_stat][gfal_plugin_statG][gfal_srm_statG][｟*｠][｟*｠] Error reported from srm_ifce : 13 [SE][Ls][SRM_AUTHORIZATION_FAILURE] User does not have valid permissions',\n",
       "       'Transfer process died with: /｟*｠/libfts_common.so.3(_ZN4fts36common5panic13get_backtraceEi+0x21) [] /｟*｠/libfts_common.so.3(+0x18f6f) [] /｟*｠/libpthread.so.0(+0xf5f0) [] /｟*｠/libpthread.so.0(raise+0x2b) [] /usr/｟*｠/gfal2-plugins/libgfal_plugin_mock.so(gfal_plugin_mock_stat+0x23b) [] /｟*｠/libgfal2.so.2(gfal_plugin_statG+0xbb) [] /｟*｠/libgfal2.so.2(gfal2_stat+0x5e) [] /｟*｠/libfts_url_copy.so(_ZN5Gfal24statER19Gfal2TransferParamsRKSsb+0xac) [] /｟*｠/libfts_url_copy.so(_ZN14UrlCopyProcess11runTransferER8TransferR19Gfal2TransferParams+0xc29) [] /｟*｠/libfts_url_copy.so(_ZN14UrlCopyProcess3runEv+0x5cb) [] fts_url_copy(main+0x103) [] /｟*｠/libc.so.6(__libc_start_main+0xf5) [] fts_url_copy(+0x6741) []',\n",
       "       'Transfer canceled', 'TRANSFER｟*｠ timed out',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: [3010]｟*｠ is no longer valid.',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR]: Got an error while querying the checksum!',\n",
       "       'error on the turl request : [SE][][SRM_INVALID_PATH] SURL is not local: srm:/lcg-se1.sfu.computecanada.ca/atlas/atlasdatadisk/rucio/',\n",
       "       'err:, err: [SE][][ETIMEDOUT] httpg:/:/srm/managerv2: User timeout over',\n",
       "       'end-of-file was reached globus_xio: An end of file occurred',\n",
       "       'and checksums do not match',\n",
       "       'error on the turl request : [SE][][SRM_AUTHORIZATION_FAILURE] access to srm:/se03.esc.qmul.ac.uk/atlas/rucio/. denied!',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy][｟*｠] SRM operation canceled',\n",
       "       'error on the turl request : [SE][][SRM_FAILURE] Unable to build the TURL for the provided transfer protocol',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy][srm_resolve_turls] SOURCE SRM_GET_TURL [srm_resolve_get_turl][｟*｠][｟*｠] error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Unable to build the TURL for the provided transfer protocol',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy][srm_resolve_turls] SOURCE SRM_GET_TURL [srm_resolve_get_turl][｟*｠][gfal_srm_mTURLS_internal][gfal_srm_getTURLS_srmv2_internal][gfal_srmv2_get_global][gfal_srm_report_error] srm-ifce err: Connection timed out, err: [SE][StatusOfGetRequest][ETIMEDOUT] httpg:/storm-se-01.ba.infn.it:8444/srm/managerv2: User timeout over',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy][srm_do_transfer][gfalt_copy_file][perform_copy][｟*｠][｟*｠] TRANSFER｟*｠',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy][srm_do_transfer][gfalt_copy_file][perform_copy][｟*｠][｟*｠] TRANSFER globus_xio: System error in: globus_xio: A system call failed:',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy][srm_do_transfer][gfalt_copy_file][perform_copy][｟*｠][｟*｠] TRANSFER globus_ftp_client: the server responded with an error｟*｠',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy][srm_do_transfer][gfalt_copy_file][perform_copy][｟*｠][｟*｠] TRANSFER an end-of-file was reached globus_xio: An end of file occurred',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy] SOURCE [][｟*｠][｟*｠] error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE]｟*｠ in PolicySource prevented PolicyCollector from establishing access rights! Processing failed!',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy] SOURCE CHECKSUM [srm_validate_source_checksum][gfal_srm_checksumG_fallback][gfal_srm_cheksumG_internal][｟*｠][｟*｠] Error reported from srm_ifce : 13 [SE][Ls][SRM_AUTHORIZATION_FAILURE] User does not have valid permissions',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): []',\n",
       "       'TRANSFER｟*｠ canceled from｟*｠',\n",
       "       'TRANSFER globus_ftp_control: gss_init_sec_context failed globus_gsi_gssapi: Unable to verify remote sides credentials globus_gsi_gssapi: SSL handshake problems: Couldnt do ssl handshake OpenSSL Error: s23_clnt.c:735: in library: SSL routines, function SSL23_GET_SERVER_HELLO: unsupported protocol',\n",
       "       'globus_ftp_client: the server responded with an error 530 530-globus_xio_gssapi_ftp.c:globus_l_xio_gssapi_ftp_decode_adat:856: 530-Authentication Error 530-GSS Major Status: Authentication Failed 530-accept_sec_context.c:gss_accept_sec_context:198: 530-SSL handshake problems 530-globus_i_gsi_gss_utils.c:globus_i_gsi_gss_handshake:1122: 530-Unable to verify remote sides credentials 530-globus_i_gsi_gss_utils.c:globus_i_gsi_gss_handshake:1095: 530-SSL handshake problems: Couldnt do ssl handshake 5',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : globus_xio_tcp_driver.c:globus_l_xio_tcp_system_connect_cb:2022: 500-Unable to connect to 2A0E:E140: 500-globus_xio_system_select.c:globus_l_xio_system_handle_write:1108: 500-System error in connect: Network is unreachable 500-globus_xio: A system call failed: Network is unreachable 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Cannot enter passive mode: java.net.SocketException: Invalid argument',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-System error in: 500-A system call failed: 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-System error in mkdir:｟*｠ or｟*｠ busy 500-A system call failed:｟*｠ or｟*｠ busy 500 End.',\n",
       "       'TRANSFER CHECKSUM MISMATCH User defined checksum and destination checksums do not match !=',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :: to connect to: error in connect: Connection 500-globus_xio: A system call failed: Connection 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :: error in: Connection reset by peer 500-globus_xio: A system call failed: Connection reset by peer 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :: Unable to connect to 2001:610:108:203A:22224 500-globus_xio: System error in connect: Permission denied 500-globus_xio: A system call failed: Permission denied 500 End.',\n",
       "       'globus_ftp_client: the server responded with an error 500 Command failed :｟*｠ error: No',\n",
       "       'TRANSFER globus_ftp_control: gss_init_sec_context failed GSS Major Status:｟*｠ Gatekeeper or Service Name globus_gsi_gssapi: Authorization denied: The name of the remote entity (/DC=org/DC=/C=/L=/O=/CN=), and the expected name for the remote entity (/CN=2001:) do not match',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : globus_xio: Unable to connect to 2001:2F8:102D:589:2:3:1: 500-globus_xio: System error in connect: Connection timed out 500-globus_xio: A system call failed: Connection timed out 500 End.',\n",
       "       'globus_ftp_client: the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Error invoking｟*｠ 530-globus_gridmap_callout_error: A GSSAPI call returned an error: Cert was not issued by correct CA. 530-globus_gridmap_callout_error: A GSSAPI call returned an error: Couldnt verify credential containing ePPN extension: unable to get local issuer certificate 530-an｟*｠ error occurred 530 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : globus_xio: The GSI XIO driver failed to establish a secure connection. The failure occured during a handshake read. 500-globus_xio: System error in recv: Connection reset by peer 500-globus_xio: A system call failed: Connection reset by peer 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : globus_xio: The GSI XIO driver failed to establish a connection via the underlying protocol. 500-globus_xio: Unable to connect to:2811 500-globus_xio: System error in connect: No route to host 500-globus_xio: A system call failed: No route to host 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : end-of-file was reached 500-globus_xio: An end of file occurred 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : callback failed. 500-globus_xio: Unable to connect to: 500-globus_xio:｟*｠ was canceled 500-globus_xio:｟*｠ timed out 500 End.',\n",
       "       'globus_ftp_client: the server responded with an error 530 530-Login incorrect. : gridmap.c:globus_gss_assist_map_and_authorize:2017: 530-Error invoking｟*｠ 530-globus_callout.c:globus_callout_handle_call_type:920: 530-The｟*｠ returned an error 530-an｟*｠ error occurred 530 End.',\n",
       "       'globus_ftp_client: the server responded with an error 451 451-GlobusError: v=1 c=INTERNAL_ERROR 451-GridFTP-Errno: 22 451-GridFTP-Reason: System error in｟*｠ in connecting to HDFS for (host=, user=cmswriter, path=/cms/phedex/store/mc/) 451-GridFTP-Error-String: Invalid argument 451',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : Failed to close file in HDFS. (host=, user=, path=/store/)',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : IPC failed while attempting to perform request',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : [｟*｠] Failed to open file.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ SRM｟*｠ aborted:｟*｠.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ Protocol｟*｠ not supported',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ 553-GlobusError: v=1 c=PATH_EXISTS 553-GridFTP-Errno: 17 553-GridFTP-Reason: System error in 553-GridFTP-Error-String: File exists｟*｠ End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ 426-GlobusError: v=1 c=DATA_CHANNEL_COMMUNICATION_FAILURE 426-GridFTP-Errno: 104 426-GridFTP-Reason: System error in name 426-GridFTP-Error-String: Connection reset by peer｟*｠ End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 550 File not found',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 550 550-GlobusError: v=1 c=PERMISSION_DENIED 550-GridFTP-Errno: 13 550-GridFTP-Reason: System error in mkdir (host=, user=cmsphedx, path=/store/generator/Summer13/GluGluToHHToTauTauBB_M-125_14TeV-powheg-pythia6/GEN/UpgrdPhase1Age5H_STAR17_61_V5A-v1/00000) 550-GridFTP-Error-String: Permission denied 550 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 530 Login failed: Request to [>gPlazma@local] timed out.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 530 Login failed: Failed to deliver LoginMessage message <:> to [>gPlazma@local]:@ is busy (its estimated response time of ms is longer than the message TTL of 30000 ms).',\n",
       "       'error on the turl request : [SE][][] <none>',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3021] Unable to get｟*｠ space -｟*｠ not defined or exhausted /eos/; Disk｟*｠',\n",
       "       'globus_ftp_client: the operation was aborted',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3009] Unable to get free physical space /eos/; No space left on device',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open error: Permission denied',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open : [ERROR] Server responded with an error: [｟*｠] Unable to open file /eos/cms/store/temp/user/; No such file or directory',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : data stream overflows buffer error: No such file or directory',\n",
       "       'TRANSFER CHECKSUM MISMATCH and',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][][｟*｠] File is.',\n",
       "       'TRANSFER CHECKSUM MISMATCH Source and destination checksums do not match 1 !=｟*｠',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Communication error on send, err: [SE][Mkdir][SRM_INTERNAL_ERROR] httpg:/:8443/srm/managerv2: srm:/:｟*｠ name space timeout',\n",
       "       'DESTINATION OVERWRITE HTTP 403 : Permission refused',\n",
       "       'DESTINATION OVERWRITE Connection timed out',\n",
       "       'DESTINATION MAKE_PARENT srm:/｟*｠:8444/srm/managerv2?SFN=/cms/store/data/Run2018D/MuOnia/RAW-RECO/LogError-PromptReco-v2/000/321/393/00000 it is a file',\n",
       "       'DESTINATION MAKE_PARENT srm:/:8444/srm/managerv2?SFN=/store/mc/ it is a file',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Permission denied, err: [SE][Mkdir][SRM_AUTHORIZATION_FAILURE] httpg:/srm-atlas.cern.ch:8443/srm/managerv2: srm:/srm-atlas.cern.ch/castor/cern.ch/grid/atlas/tzero/user/mlassnig/pilot/user.mlassnig.pilot.test.single.hits: No such file or directory',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Permission denied, err: [SE][Mkdir][SRM_AUTHORIZATION_FAILURE] httpg:/:8443/srm/managerv2: srm:/castor/ads.rl.ac.uk/prod/: User can not create a directory at this level',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: No such file or directory, err: [SE][Mkdir][SRM_INVALID_PATH] httpg:/:8443/srm/managerv2: No such file or directory',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Communication error on send, err: [SE][Mkdir][] httpg:/lcg-se1.sfu.computecanada.ca:8443/srm/managerv2: org.apache.axis.types.URI$MalformedURIException: Scheme specific part cannot be empty.',\n",
       "       'DESTINATION EXISTS Destination already｟*｠ gsiftp:/eoscmsftp.cern.ch/eos/cms/store/mc/GEN/106X_upgrade2018_realistic_v4-v1/, Cancel',\n",
       "       'DESTINATION OVERWRITE Result Could not connect to server after 1 attempts',\n",
       "       'DESTINATION CHECKSUM globus_xio: Unable to connect to:2811 globus_xio: System error in connect: Connection refused globus_xio: A system call failed: Connection refused',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error 550 Error retrieving /pnfs/nikhef.nl/data/atlas/atlasdatadisk/rucio/mc15_13TeV/TXT.13045593.: No such file or directory /pnfs/nikhef.nl/data/atlas/atlasdatadisk/rucio/mc15_13TeV/TXT.13045593.',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error 500 500-globus_xio: The GSI XIO driver failed to establish a connection via the underlying protocol. 500-globus_xio: Unable to connect to:2811 500-globus_xio: System error in connect: Connection refused 500-globus_xio: A system call failed: Connection refused 500 End.',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error 500 500-Command failed : globus_xio_register_open failed. 500-globus_xio: Unable to open file /lustre/cms/store/user/ 500-globus_xio: System error in open: No such file or directory 500-globus_xio: A system call failed: No such file or directory 500 End.',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error 500 500-Command failed : System error in name: Connection timed out 500-A system call failed: Connection timed out 500 End.',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error 451 451-GlobusError: v=1 c=INTERNAL_ERROR 451-GridFTP-Errno: 110 451-GridFTP-Reason: System error in name 451-GridFTP-Error-String: Connection timed out 451 End.',\n",
       "       'DESTINATION CHECKSUM error on the turl request : [SE][StatusOfGetRequest][SRM_REQUEST_QUEUED] All chunks successfully handled!',\n",
       "       'DESTINATION CHECKSUM error on the turl request : [SE][StatusOfGetRequest][SRM_INVALID_PATH] The requested file｟*｠ does not｟*｠, or it is a directory!',\n",
       "       'DESTINATION OVERWRITE Result (Neon): Could not read status｟*｠: Connection reset by peer after 1 attempts',\n",
       "       'DESTINATION OVERWRITE error reported from srm_ifce, [SE][srmRm][SRM_AUTHORIZATION_FAILURE] File not｟*｠, permission denied.',\n",
       "       'Source and destination file｟*｠',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/lcg-se1.sfu.computecanada.ca/atlas/rucio/ while putdone : [SE][PutDone][SRM_INVALID_PATH] SURL is not local: srm:/lcg-se1.sfu.computecanada.ca/atlas/rucio/',\n",
       "       'DESTINATION SRM_PUTDONE call to srm_ifce error: [SE][PutDone][] httpg:/:8443/srm/managerv2:',\n",
       "       'DESTINATION SRM_PUTDONE call to srm_ifce error: [SE][PutDone][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports:',\n",
       "       'DESTINATION SRM_PUTDONE call to srm_ifce error: [SE][PutDone][SRM_FAILURE] httpg:/se03.esc.qmul.ac.uk:8444/srm/managerv2: Failed to authorize XACML request: Timeout was reached.',\n",
       "       'DESTINATION SRM_PUTDONE call to srm_ifce error: [SE][PutDone][ETIMEDOUT] httpg:/｟*｠:8444/srm/managerv2: User timeout over',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/storm-se-01.ba.infn.it/cms/store/user/raly/MonoHiggs/FullRunII/Data2017processing/ while putdone : [SE][PutDone][SRM_INVALID_PATH] PtP status for this SURL is SRM_ABORTED',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/storage01.lcg.cscs.ch/pnfs/lcg.cscs.ch/cms/trivcat/store/PhEDEx_LoadTest07/ while putdone : [SE][PutDone][SRM_INVALID_PATH] No such file or directory: /pnfs/lcg.cscs.ch/cms/trivcat/store/PhEDEx_LoadTest07/',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/se01.indiacms.res.in/dpm/indiacms.res.in/home/cms/store/user/ while putdone : [SE][PutDone][SRM_INTERNAL_ERROR] Timed out',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/pnfs/data/cms/store/PhEDEx_LoadTest07/ while putdone : [SE][PutDone][SRM_INVALID_PATH]:pnfs/data/cms/store/PhEDEx_LoadTest07/',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/dpm/home/atlas/rucio/user/. while putdone : [SE][PutDone][SRM_FILE_LIFETIME_EXPIRED] <none>',\n",
       "       'DESTINATION OVERWRITE error reported from srm_ifce, [SE][srmRm][SRM_AUTHORIZATION_FAILURE] User is not｟*｠ to｟*｠ file',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/data/atlas/atlasdatadisk/rucio/. while putdone : [SE][PutDone][SRM_ABORTED] The SURL has been aborted.',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/data/ while putdone : [SE][PutDone][SRM_INTERNAL_ERROR] PreparedStatementCallback; SQL [UPDATE t_inodes SET inlink=inlink +?,imtime=?,ictime=?,igeneration=igeneration+1 WHERE inumber=?]; ERROR:｟*｠ detected; Detail: Process',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/cms/store/user/0000/ while putdone : [SE][PutDone][] for',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/atlas/atlasdatadisk/rucio/mc16_13TeV/. while putdone : [SE][PutDone][SRM_INVALID_PATH] PtP status for this SURL is SRM_ABORTED',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/ while putdone : [SE][PutDone][SRM_INTERNAL_ERROR] Request to [>PnfsManager@local] timed out.',\n",
       "       'DESTINATION OVERWRITE｟*｠:｟*｠ HTTP 500 :｟*｠ server error: 500 with url davs:/dcgftp.usatlas.bnl.gov:443/pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/tests/',\n",
       "       'DESTINATION OVERWRITE｟*｠:｟*｠ HTTP 403 : Permission refused',\n",
       "       'DESTINATION OVERWRITE error reported from srm_ifce, [SE][srmRm][SRM_INTERNAL_ERROR]',\n",
       "       'DESTINATION CHECKSUM error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Local filesystem mask does not allow setting up correct ACLs for PtG!',\n",
       "       'DESTINATION CHECKSUM checksum calculation for ADLER32 not supported for davs:/atlas-fed-fe1.triumf.ca:443/dynafed/atlas/atlasdatadisk/rucio/mc16_13TeV/HITS.10701323.',\n",
       "       'DESTINATION CHECKSUM checksum calculation for ADLER32 not supported for davs:/:443/dpm/home/atlas/atlasdatadisk/rucio/mc16_13TeV/ad/dc/log.20115295._000026.job.log.tgz.1',\n",
       "       ': the server responded with an error 500 Command failed :｟*｠ server error',\n",
       "       ': the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c: in library: SSL routines, function: certificate｟*｠: Could not verify credential｟*｠: The certificate: with subject: /=/=/OU=/CN=/CN=/CN=/CN=',\n",
       "       ': the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Gridmap｟*｠ failure: Could not map /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=/CN=/CN= 530- 530 End.',\n",
       "       ': the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Error invoking｟*｠ 530-globus_callout_module: The｟*｠ returned an error 530-an｟*｠ error occurred 530 End.',\n",
       "       ': the server responded with an error 530 530-Login incorrect. : /builddir/build/BUILD/gridftp-hdfs-1.1.1/src/gridftp_hdfs.c:hdfs_start:756: 530-Server is cancelling transfer due to over-load limit (host=gftp-3.t2.ucsd.edu, user=, path=(null) 530 End.',\n",
       "       ': the server responded with an error 500 failed. 500-globus_xio: Unable to open file /cms/data/store/mc/RunIIFall17MiniAODv2/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/ 500-globus_xio: System error in open: Permission denied 500-globus_xio: A system call failed: Permission denied 500 End.',\n",
       "       ': the server responded with an error 500 error in: No such file or directory 500-A system call failed: No such file or directory 500 End.',\n",
       "       ': the server responded with an error 500 callback failed. 500-globus_xio: System error in read: Input/output error 500-globus_xio: A system call failed: Input/output error 500 End.',\n",
       "       ': the server responded with an error 500 an｟*｠ error occurred',\n",
       "       ': the server responded with an error 500 500-Command failed : System error in: Permission denied 500-A system call failed: Permission denied 500 End.',\n",
       "       'DESTINATION CHECKSUM MISMATCH Source and destination ADLER32 do not match ( !=)',\n",
       "       ': the server responded with an error 451 451-GlobusError: v=1 c=INTERNAL_ERROR 451-GridFTP-Errno: 451-GridFTP-Reason: System error in 451-GridFTP-Error-String: 451 End.',\n",
       "       ': the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.',\n",
       "       ': the server responded with an error 421 Idle Timeout:｟*｠ control connection.',\n",
       "       ': Unable to connect to:2811 globus_xio: globus_libc_getaddrinfo failed. globus_common: Temporary failure in name｟*｠',\n",
       "       ': Unable to connect to:2811 globus_xio: globus_libc_getaddrinfo failed. globus_common: Name or service not known',\n",
       "       ': Unable to connect to: globus_xio: System error in connect: Connection globus_xio: A system call failed: Connection',\n",
       "       ': System error in: Connection reset by peer globus_xio: A system call failed: Connection reset by peer',\n",
       "       ': System error in send:｟*｠ globus_xio: A system call failed:｟*｠',\n",
       "       ': the server responded with an error 530 530-globus_xio: Authentication Error｟*｠: Could not verify credential｟*｠: Could not verify credential｟*｠: Invalid｟*｠: The available｟*｠ has expired 530 End.',\n",
       "       ': the server responded with an error 530 Login incorrect. : Invalid group id｟*｠ to user.',\n",
       "       ': the server responded with an error 530 Login incorrect. : Server is cancelling transfer due to over-load limit (host=, user=, path=(null)',\n",
       "       ': the server responded with an error 530 Login incorrect. : Server over the global connection limit of 250 (user has 0 transfers) (host=, user=cms, path=(null)',\n",
       "       'DESTINATION CHECKSUM Connection Timeout during redirection on https:/:1094/cephfs/grid/atlas/atlaslocalgroupdisk/rucio/tests/?authz=Bearer%',\n",
       "       'Connection timed out', 'Connection refused',\n",
       "       'Connection Timeout during redirection on https:/:1094/cephfs/grid/atlas/atlaslocalgroupdisk/rucio/user/amelzer/user.amelzer.20070922.EXT0.?authz=Bearer%',\n",
       "       'Checksum value required if mode is not end to end',\n",
       "       'CHECKSUM｟*｠ timed out', 'CHECKSUM timeout of｟*｠',\n",
       "       'CHECKSUM globus_ftp_client: the server responded with an error 500｟*｠ server error 500- 500 End.',\n",
       "       'CHECKSUM globus_ftp_client: the operation was aborted',\n",
       "       'CHECKSUM HTTP 500 :｟*｠ server error: 500',\n",
       "       'CHECKSUM HTTP 404 : File not found',\n",
       "       'Authentication error, reached maximum number of attempts',\n",
       "       ': the server responded with an error 550 550-GlobusError: v=1 c=PATH_NOT_FOUND 550-GridFTP-Errno: 2 550-GridFTP-Reason: System error in 550-GridFTP-Error-String: No such file or directory 550 End.',\n",
       "       ': the server responded with an error 550 550-GlobusError: v=1 c= 550-GridFTP-Errno: 550-GridFTP-Reason: System error in name 550-GridFTP-Error-String: 550 End.',\n",
       "       ': the server responded with an error 535 Authentication failed: The peers certificate with subjects DN CN= was rejected. The peers certificate status is: FAILED The following validation errors were found: error at position in chain, problematic certificate subject: CN=',\n",
       "       ': the server responded with an error 530 Login incorrect. : an｟*｠ error occurred',\n",
       "       ': the server responded with an error 530 Login incorrect. : Server over the user connection limit of (host=, user=)',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl gsiftp:/:2811/gpfs/storage_3/atlas/atlasdatadisk/rucio/mc16_13TeV/HITS.19909364. request : [SE][StatusOfPutRequest][SRM_ABORTED] File has been｟*｠.',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][PrepareToPut][SRM_EXCEED_ALLOCATION] Space associated with the space token 30043703 is not enough to hold SURL.',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_DUPLICATION_ERROR] Cannot srmPut file because it already exists!',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory /pnfs/data/cms/store/',\n",
       "       'HTTP 404 : File not found after 1 attempts',\n",
       "       'HTTP 403 : Permission refused',\n",
       "       'Failed to stat file (Permission denied)',\n",
       "       'Failed to stat file (No such file or directory)',\n",
       "       'Failed to stat file (No route to host)',\n",
       "       'Error reported from srm_ifce : 70 [SE][Ls][SRM_INTERNAL_ERROR] TTL exceeded',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] SURL is not local: srm:/madhatter.csc.fi/pnfs/csc.fi/data/cms/store/data/',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory /pnfs/gridka.de/cms/disk-only/store/data/Run2017F/BTagMu/MINIAOD/31Mar2018-v1/100000/1E2E29A7-B638-E811-BCD3-A4BF01125C30.root',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory /pnfs/data/cms/disk/store/temp/user/welmeten.3257b2c1348f232024e043daaeb0ca1bdcc78c41/HiggsNtuples2018DataLegacy/SingleMuon/',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] connection timed out: lcg-se01.icepp.jp/2001:2f8:102d:589:2:1:2:1:1094',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] File does not｟*｠',\n",
       "       'Error reported from srm_ifce : 16 [SE][Ls][SRM_FILE_BUSY] The requested SURL is locked by an｟*｠.',\n",
       "       'Error reported from srm_ifce : 13 [SE][Ls][SRM_AUTHORIZATION_FAILURE] No｟*｠ found for user!',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [｟*｠]｟*｠ limit has been reached',\n",
       "       'Error on XrdCl:CopyProcess:Run(): []',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR]｟*｠ not supported: does not support third-party-copy',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR]｟*｠ error: Connection timed out',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR]: Got while querying the checksum!',\n",
       "       'HTTP 500 :｟*｠ server error: 500 after 1 attempts',\n",
       "       'No such file or directory',\n",
       "       'Protocol not supported or path/url invalid: root:/:1094/atlasscratchdisk/rucio/tests/',\n",
       "       'SOURCE CHECKSUM Connection Timeout during redirection on https:/:1094/store/PhEDEx_LoadTest07/LoadTest07_Debug_US_Florida/US_Nebraska/460/?authz=Bearer%',\n",
       "       'SRM operation canceled',\n",
       "       'SOURCE SRM_GET_TURL srm-ifce err: Invalid request descriptor, err: [SE][StatusOfGetRequest][SRM_INVALID_REQUEST] httpg:/se01.dur.scotgrid.ac.uk:8446/srm/managerv2: Unknown request token',\n",
       "       'SOURCE SRM_GET_TURL srm-ifce err: Connection reset by peer, err: [SE][｟*｠][] httpg:/srm-eoslhcb.cern.ch:8443/srm/v2/server: CGSI-gSOAP running on reports Error reading token data header: Connection reset by peer',\n",
       "       ': System error in recv: Connection timed out globus_xio: A system call failed: Connection timed out',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_INTERNAL_ERROR]｟*｠',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FILE_BUSY] Requested file is busy ( ongoing putrequest on the same file',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Local filesystem!',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Insufficient user privileges to trigger a tape recall or file replication to the t0cms service class',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Failed to pin file [rc=｟*｠=｟*｠ was aborted].',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Failed to pin file [rc=10011,msg= not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after.].',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][PrepareToGet][SRM_FAILURE] srm:/srm-eoslhcb.cern.ch/eos/｟*｠/grid/prod/｟*｠/MC/ALLSTREAMS.DST/0000/ is not a supported url.',\n",
       "       'SOURCE SRM_GET_TURL The｟*｠ file is not｟*｠',\n",
       "       'SOURCE CHECKSUM globus_ftp_client: the server responded with an error 550 550-GlobusError: v=1 c=PATH_NOT_FOUND 550-GridFTP-Errno: 2 550-GridFTP-Reason: System error in Failed to open file for checksumming (host=, user=cmsu0982, path=/cms/store/temp/user/fbrivio.39c47ce16ae86ca0e76dd41b21a1e05263edba45/Hhh_1718/',\n",
       "       'SOURCE CHECKSUM globus_ftp_client: the server responded with an error 504 Checksum is not available, dynamic checksum calculation is not supported',\n",
       "       'SOURCE CHECKSUM globus_ftp_client: the server responded with an error 500 error:｟*｠ denied',\n",
       "       'SOURCE CHECKSUM MISMATCH User defined checksum and｟*｠ checksum do not match !=',\n",
       "       'SOURCE CHECKSUM HTTP 403 : Permission refused',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠]:/｟*｠:1094',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: [｟*｠] Unable to read /｟*｠/atlas/tpctest/test/;',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_DUPLICATION_ERROR] File exists and overwrite｟*｠ is｟*｠',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INVALID_PATH] Failed to put /storage/data/cms/store/',\n",
       "       'Destination file exists and overwrite is not enabled',\n",
       "       'DESTINATION error on the turl request : [SE][][｟*｠] chunk is being processed!',\n",
       "       'DESTINATION error on the turl request : [SE][][SRM_FAILURE] Unable to store the request in StoRM DB',\n",
       "       'DESTINATION SRM_PUT_TURL srm-ifce err: Communication error on send, err: [SE][｟*｠][SRM_INTERNAL_ERROR] httpg:/｟*｠:8443/srm/managerv2: SRM backend serving this request is currently offline.',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][]/belle/4S/!',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][] error accessing belle2grid4.cc.ntu.edu.tw:/belle/2020-01-02: out',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INVALID_PATH] The requested SURL is: srm:/srm01.ifca.es:8444/cms/store/user/fernanpe/CRAB_PrivateMC/0000/log/, but its parent srm:/srm01.ifca.es:8444/cms/store/user/fernanpe/CRAB_PrivateMC/0000/log/does not｟*｠!',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INVALID_PATH] Parent //cms/store/ doesnt｟*｠!',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INTERNAL_ERROR] Request to [>PnfsManager@local] timed out.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: [｟*｠] Unable to open /dpm/home/atlas/atlasscratchdisk/rucio/tests/; Server error: No such file or directory',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INTERNAL_ERROR] Local filesystem has problems manipulating ACE!',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INTERNAL_ERROR] Failed to｟*｠ transfers',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY]｟*｠ is ongoing for this file',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY] The surl srm:/storm-fe.cr.cnaf.infn.it/atlas/atlasmctape/mc16_13TeV/AOD/e7818_e7400_a875_r9364_r9315/mc16_13TeV.411180.PhPy8EG_A14_NNPDF30ME_ttbb_4FS_MS_lminus.merge.AOD.e7818_e7400_a875_r9364_r9315_tid19491618_00/AOD.19491618. is curr',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY] The surl srm:/store/mc/ is currently busy',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FAILURE] error chowning｟*｠:/cms/:｟*｠ not permitted (error 1 on｟*｠)',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FAILURE] error accessing grid30.physics.uoi.gr:/102/2020-01-03: Connection closed by remote end',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FAILURE] Space Management｟*｠ in srmPrepareToPut failed!',\n",
       "       'ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Remote copy failed with status code 0:｟*｠ too slow. Less than 1048576 bytes/sec transferred the last 120 seconds',\n",
       "       'ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: failed to connect to server:',\n",
       "       'ERROR: Copy failed with mode 3rd, with error:',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3003] Output file /dpm/brunel.ac.uk/home/dteam/wlcg-tpc/root/ is already opened by 1 writer; open denied.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: [] Unable to open /dpm/home/dteam/root/test/;',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: [] Unable to //atlasscratchdisk/rucio/tests/;',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: []',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] Unable to close file ; invalid argument',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] Unable to checksum /dpm/home/; invalid argument Got an error while querying the checksum!',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [] Unable to /dpm/home/dteam/root/test/;',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [] No response from server after 30 seconds.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Invalid request; user not｟*｠',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012]｟*｠ failed Got an error while querying the checksum!',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/:/atlasscratchdisk/rucio/tests/?fst.readahead=true',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010]｟*｠ is no longer valid.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open - tpc key replayed /eos/; operation not permitted',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to /dpm/home/atlas/atlasscratchdisk/rucio/tests/;',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to //; permission denied',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests/',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3003] Output file /dteam:test1/domatest/ is already opened by 1 writer; open denied.',\n",
       "       '｟*｠ timed out'], dtype=object)"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster.result['pattern'].values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "clusters, outliers = cluster.split_clusters(cluster.result, 'cluster_size', threshold=30)\n",
    "outliers #clusters containing fewer than 3 messages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cluster_name</th>\n",
       "      <th>cluster_size</th>\n",
       "      <th>pattern</th>\n",
       "      <th>mean_similarity</th>\n",
       "      <th>std_similarity</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>238</td>\n",
       "      <td>6</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 451 General problem:</td>\n",
       "      <td>0.82</td>\n",
       "      <td>0.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>255</td>\n",
       "      <td>3</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error｟*｠</td>\n",
       "      <td>0.94</td>\n",
       "      <td>0.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>261</td>\n",
       "      <td>3</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : error in: system call failed: 500 End.</td>\n",
       "      <td>0.88</td>\n",
       "      <td>0.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>24</td>\n",
       "      <td>196</td>\n",
       "      <td>2</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to select｟*｠:｟*｠</td>\n",
       "      <td>0.90</td>\n",
       "      <td>0.10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>13</td>\n",
       "      <td>109</td>\n",
       "      <td>2</td>\n",
       "      <td>DESTINATION SRM_PUT_TURL error on the turl request : [SE][][]</td>\n",
       "      <td>0.89</td>\n",
       "      <td>0.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>12</td>\n",
       "      <td>262</td>\n",
       "      <td>2</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : 500-globus_xio: System error in: 500-globus_xio: A system call failed: 500 End.</td>\n",
       "      <td>0.94</td>\n",
       "      <td>0.06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>11</td>\n",
       "      <td>99</td>\n",
       "      <td>2</td>\n",
       "      <td>DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY] The surl srm:/ is currently busy (ongoing put</td>\n",
       "      <td>0.94</td>\n",
       "      <td>0.06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>10</td>\n",
       "      <td>97</td>\n",
       "      <td>2</td>\n",
       "      <td>DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][] error accessing:/:</td>\n",
       "      <td>0.91</td>\n",
       "      <td>0.09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>9</td>\n",
       "      <td>276</td>\n",
       "      <td>2</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : Error｟*｠</td>\n",
       "      <td>0.91</td>\n",
       "      <td>0.09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>7</td>\n",
       "      <td>285</td>\n",
       "      <td>2</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. :</td>\n",
       "      <td>0.88</td>\n",
       "      <td>0.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>5</td>\n",
       "      <td>46</td>\n",
       "      <td>2</td>\n",
       "      <td>DESTINATION CHECKSUM checksum calculation for ADLER32 not supported for davs:/:/atlasscratchdisk/rucio/tests/</td>\n",
       "      <td>0.98</td>\n",
       "      <td>0.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>36</td>\n",
       "      <td>2</td>\n",
       "      <td>: the server responded with an error 500｟*｠ server error</td>\n",
       "      <td>0.95</td>\n",
       "      <td>0.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>14</td>\n",
       "      <td>118</td>\n",
       "      <td>2</td>\n",
       "      <td>: Copy failed with mode 3rd push, with error: Transfer failed: failure: sending data</td>\n",
       "      <td>0.89</td>\n",
       "      <td>0.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>(Neon): SSL handshake failed: Connection timed out during SSL handshake</td>\n",
       "      <td>0.90</td>\n",
       "      <td>0.10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>8</td>\n",
       "      <td>80</td>\n",
       "      <td>2</td>\n",
       "      <td>DESTINATION SRM_PUTDONE Error on the surl srm:/dpm/home/ while putdone : [SE][PutDone][]</td>\n",
       "      <td>0.99</td>\n",
       "      <td>0.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>15</td>\n",
       "      <td>31</td>\n",
       "      <td>2</td>\n",
       "      <td>error, reached maximum number of attempts after 1 attempts</td>\n",
       "      <td>0.93</td>\n",
       "      <td>0.07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>6</td>\n",
       "      <td>305</td>\n",
       "      <td>2</td>\n",
       "      <td>[gfalt_copy_file][perform_copy] TRANSFER [gfal_http_copy] ERROR: Copy failed with mode 3rd push, with error: [davix2gliberr]</td>\n",
       "      <td>0.92</td>\n",
       "      <td>0.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>17</td>\n",
       "      <td>131</td>\n",
       "      <td>2</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.96</td>\n",
       "      <td>0.04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>25</td>\n",
       "      <td>191</td>\n",
       "      <td>2</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure:</td>\n",
       "      <td>0.93</td>\n",
       "      <td>0.07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>16</td>\n",
       "      <td>239</td>\n",
       "      <td>2</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Failed to connect [:]: Connection</td>\n",
       "      <td>0.95</td>\n",
       "      <td>0.05</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    cluster_name  cluster_size  \\\n",
       "0   238           6              \n",
       "1   255           3              \n",
       "2   261           3              \n",
       "24  196           2              \n",
       "13  109           2              \n",
       "12  262           2              \n",
       "11  99            2              \n",
       "10  97            2              \n",
       "9   276           2              \n",
       "7   285           2              \n",
       "5   46            2              \n",
       "4   36            2              \n",
       "14  118           2              \n",
       "3   0             2              \n",
       "8   80            2              \n",
       "15  31            2              \n",
       "6   305           2              \n",
       "17  131           2              \n",
       "25  191           2              \n",
       "16  239           2              \n",
       "\n",
       "                                                                                                                                                                     pattern  \\\n",
       "0   TRANSFER globus_ftp_client: the server responded with an error 451 General problem:                                                                                        \n",
       "1   TRANSFER globus_ftp_client: the server responded with an error｟*｠                                                                                                          \n",
       "2   TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : error in: system call failed: 500 End.                                            \n",
       "24  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to select｟*｠:｟*｠                                                              \n",
       "13  DESTINATION SRM_PUT_TURL error on the turl request : [SE][][]                                                                                                              \n",
       "12  TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : 500-globus_xio: System error in: 500-globus_xio: A system call failed: 500 End.   \n",
       "11  DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY] The surl srm:/ is currently busy (ongoing put                                 \n",
       "10  DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][] error accessing:/:                                                                         \n",
       "9   TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : Error｟*｠                                                                              \n",
       "7   TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. :                                                                                       \n",
       "5   DESTINATION CHECKSUM checksum calculation for ADLER32 not supported for davs:/:/atlasscratchdisk/rucio/tests/                                                              \n",
       "4   : the server responded with an error 500｟*｠ server error                                                                                                                   \n",
       "14  : Copy failed with mode 3rd push, with error: Transfer failed: failure: sending data                                                                                       \n",
       "3   (Neon): SSL handshake failed: Connection timed out during SSL handshake                                                                                                    \n",
       "8   DESTINATION SRM_PUTDONE Error on the surl srm:/dpm/home/ while putdone : [SE][PutDone][]                                                                                   \n",
       "15  error, reached maximum number of attempts after 1 attempts                                                                                                                 \n",
       "6   [gfalt_copy_file][perform_copy] TRANSFER [gfal_http_copy] ERROR: Copy failed with mode 3rd push, with error: [davix2gliberr]                                               \n",
       "17  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                               \n",
       "25  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure:                                                                                      \n",
       "16  TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Failed to connect [:]: Connection                                                      \n",
       "\n",
       "    mean_similarity  std_similarity  \n",
       "0   0.82             0.11            \n",
       "1   0.94             0.05            \n",
       "2   0.88             0.08            \n",
       "24  0.90             0.10            \n",
       "13  0.89             0.11            \n",
       "12  0.94             0.06            \n",
       "11  0.94             0.06            \n",
       "10  0.91             0.09            \n",
       "9   0.91             0.09            \n",
       "7   0.88             0.12            \n",
       "5   0.98             0.02            \n",
       "4   0.95             0.05            \n",
       "14  0.89             0.11            \n",
       "3   0.90             0.10            \n",
       "8   0.99             0.01            \n",
       "15  0.93             0.07            \n",
       "6   0.92             0.08            \n",
       "17  0.96             0.04            \n",
       "25  0.93             0.07            \n",
       "16  0.95             0.05            "
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "top_clusters = cluster.validation(clusters).sort_values(by=[\"cluster_size\"], ascending=False) #clusters sorted by similarity inside the cluster\n",
    "top_clusters.head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "11.704834605597965\n",
      "100.25445292620864\n"
     ]
    }
   ],
   "source": [
    "print(top_clusters['cluster_size'].head(20).sum()/(df.shape[0]-1)*100)\n",
    "print(clusters['cluster_size'].sum()/(df.shape[0]-1)*100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'tokenization': 0.1474,\n",
       " 'group_equals': 0.4371,\n",
       " 'matching_clusterization': 0.7095,\n",
       " 'process': 1.294,\n",
       " 'validation': 0.1809}"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster.timings"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "top_clusters['pattern'].to_csv(\"patterns.txt\",index=False, header=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
